// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prueba_Tecnica__I_D_i_d.Data;

#nullable disable

namespace Prueba_Tecnica__I_D_i_d.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Prueba_Tecnica__I_D_i_d.Modelo.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Celular")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Correo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Prueba_Tecnica__I_D_i_d.Modelo.Estados", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("Prueba_Tecnica__I_D_i_d.Modelo.Habitaciones", b =>
                {
                    b.Property<int>("HabitacionesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CupoMaximo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdSede")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoHabitacion")
                        .HasColumnType("INTEGER");

                    b.HasKey("HabitacionesId");

                    b.ToTable("Habitaciones");
                });

            modelBuilder.Entity("Prueba_Tecnica__I_D_i_d.Modelo.Reservas", b =>
                {
                    b.Property<int>("ReservasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCliente")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdHabitacion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdSede")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReservasId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Prueba_Tecnica__I_D_i_d.Modelo.Sede", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdHabitacion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTemporada")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreSede")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroHabitaciones")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Sedes");
                });

            modelBuilder.Entity("Prueba_Tecnica__I_D_i_d.Modelo.Temporadada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreTemporada")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Temporadas");
                });

            modelBuilder.Entity("Prueba_Tecnica__I_D_i_d.Modelo.TipoHabitacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreTipoHabitacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tarifa")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TipoHabitaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
